spring:
  application:
    name: data-generator

server:
  port: 8099

mybatis:
  #指定Mybatis的实体目录
  type-aliases-package: com.sparkler.generator.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*xml

async:
  executor:
    thread:
      # 是否根据CPU配置来生成核心线程配置 0 是；1 否；
      auto_set_pool_size: 0
      # 核心线程数
      core_pool_size: 4
      # 最大线程数
      max_pool_size: 8
      # 配置队列大小
      queue_capacity: 200
      name:
        # 配置线程池中线程的名称前缀
        prefix: DATA-GENERATOR