spring:
  application:
    name: data-generator
  datasource:
    druid:
      url: jdbc:mysql://rds-aliyun.mysql.rds.aliyuncs.com:3306/datagenerator?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: "@Root#1203"
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 5
      maxActive: 100
      # 获取数据库连接等待的超时时间
      maxWait: 60000
      maxOpenPreparedStatements: -1
      # 系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      validationQuery: SELECT 1
      # 启用空闲连接检测，以便回收
      testWhileIdle: true
      # 从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      testOnBorrow: false
      # 释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      testOnReturn: false
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      # 配置连接在池中的最大生存时间
      maxEvictableIdleTimeMillis: 400000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 设置链接超时回收
      removeAbandoned: true
      # 从获取到链接开始，超过这么长时间，链接将被连接池强制回收
      removeAbandonedTimeout: 180
      # 强制回收链接是，将堆栈追踪信息打印到日志中
      logAbandoned: true
      breakAfterAcquireFailure: true
      connectionErrorRetryAttempts: 0

server:
  port: 8099
mybatis:
  #指定Mybatis的实体目录
  type-aliases-package: com.sparkler.generator.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*xml


async:
  executor:
    thread:
      # 核心线程数
      core_pool_size: 4
      # 最大线程数
      max_pool_size: 8
      # 配置队列大小
      queue_capacity: 200
      name:
        # 配置线程池中线程的名称前缀
        prefix: DATA-GENERATOR